/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auditHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents recorded, most recently updated first */
        get: operations["listDossiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossiers/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns the dossier as JSON. Append `.pdf` to the incident id to receive
         *     the rendered document instead.
         */
        get: operations["getDossier"];
        put?: never;
        /**
         * Generate (or regenerate) the dossier for an incident
         * @description Generation is automatic when containment completes. This endpoint is for
         *     regenerating after later events, such as a customer answering.
         */
        post: operations["generateDossier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossiers/{incidentId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recompute the hash chain
         * @description Answers "is this still intact?" without re-reading the document. A broken
         *     chain returns 200 with `verified: false` and names the first bad record,
         *     because an auditor needs the detail, not an error code.
         */
        get: operations["verifyChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossiers/{incidentId}/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The raw hash chain
         * @description Hands over the records so a recipient can verify with their own code
         *     rather than taking this service's word for it.
         */
        get: operations["getChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            /** @enum {string} */
            bus?: "up" | "down";
        };
        Error: {
            code: string;
            message: string;
        };
        Record: {
            seq: number;
            event_id: string;
            event_type: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            recorded_at?: string;
            producer?: string;
            causation_id?: string;
            /** @description redacted payload */
            payload?: Record<string, never>;
            /** @description hash of the original */
            payload_hash: string;
            prev_hash: string;
            record_hash: string;
            redacted_fields?: string[];
        };
        Chain: {
            incident_id: string;
            head: string;
            /** Format: date-time */
            opened_at?: string;
            /** Format: date-time */
            updated_at?: string;
            records: components["schemas"]["Record"][];
        };
        Summary: {
            hazard?: string;
            classification?: string;
            sources?: string[];
            products?: string[];
            lots_held?: string[];
            /** @enum {string} */
            scope?: "LOT" | "SKU";
            decision?: string;
            decided_by?: string;
            confidence?: number;
            threshold?: number;
            units_held?: number;
            units_left_sellable?: number;
            customers_offered?: number;
            customers_answered?: number;
            notifications_sent?: number;
            evasion_flags?: number;
            redacted_fields?: string[];
        };
        TimelineEntry: {
            seq?: number;
            /** Format: date-time */
            at?: string;
            actor?: string;
            event?: string;
            detail?: string;
        };
        Dossier: {
            dossier_id: string;
            incident_id: string;
            /** Format: date-time */
            generated_at: string;
            /** @description the chain head */
            content_hash: string;
            /** @enum {string} */
            hash_algorithm: "sha256";
            /** @description base64 RFC 3161 token over the chain head */
            timestamp_proof?: string;
            /** @description why no proof is present */
            timestamp_note?: string;
            event_count: number;
            /** Format: date-time */
            opened_at?: string;
            /** Format: date-time */
            closed_at?: string;
            summary?: components["schemas"]["Summary"];
            timeline?: components["schemas"]["TimelineEntry"][];
            chain?: components["schemas"]["Record"][];
        };
    };
    responses: {
        /** @description no such incident, or no dossier generated for it */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auditHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listDossiers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            incident_id: string;
                            has_dossier: boolean;
                            event_count: number;
                            content_hash?: string;
                        }[];
                    };
                };
            };
        };
    };
    getDossier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the dossier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dossier"];
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    generateDossier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dossier"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        incident_id: string;
                        verified: boolean;
                        events: number;
                        content_hash?: string;
                        hash_algorithm?: string;
                        /** @description present when verified is false */
                        problem?: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chain"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
