/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rescueHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rescues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRescues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rescues/{rescueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Storefront loads this from the link in the customer email/SMS. */
        get: operations["getRescue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rescues/{rescueId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explicit customer click-to-confirm; emits order.rescue.confirmed.v1 */
        post: operations["confirmRescue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            /** @enum {string} */
            bus?: "up" | "down";
        };
        Error: {
            code: string;
            message: string;
        };
        Money: {
            amount_minor: number;
            currency: string;
        };
        AffectedLine: {
            line_item_id: string;
            gtin: string;
            sku?: string;
            product_title?: string;
            lot_code: string;
            quantity: number;
            unit_price: components["schemas"]["Money"];
        };
        RescueOption: {
            option_id: string;
            /** @enum {string} */
            kind: "SUBSTITUTE" | "REFUND" | "CANCEL";
            gtin?: string;
            sku?: string;
            product_title?: string;
            unit_price?: components["schemas"]["Money"];
            allergen_safe?: boolean;
            allergens?: string[];
            rationale?: string;
        };
        Rescue: {
            rescue_id: string;
            incident_id: string;
            order_id: string;
            /** @enum {string} */
            status: "PROPOSED" | "CONFIRMED" | "EXPIRED";
            hazard?: string;
            /** Format: date-time */
            proposed_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            confirmed_at?: string;
            chosen_option_id?: string;
            affected_line: components["schemas"]["AffectedLine"];
            options: components["schemas"]["RescueOption"][];
        };
    };
    responses: {
        /** @description not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description invalid consent token */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description already confirmed or expired */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rescueHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listRescues: {
        parameters: {
            query?: {
                order_id?: string;
                incident_id?: string;
                status?: "PROPOSED" | "CONFIRMED" | "EXPIRED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description rescues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Rescue"][];
                    };
                };
            };
        };
    };
    getRescue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rescueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the rescue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rescue"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    confirmRescue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rescueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    option_id: string;
                    /** @description issued with the proposal, proves the click came from the notified customer */
                    consent_token: string;
                };
            };
        };
        responses: {
            /** @description rescue after confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rescue"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
