/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resolutionHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lots/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verified Safe Lot check */
        get: operations["getLotStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            /** @enum {string} */
            bus?: "up" | "down";
        };
        Error: {
            code: string;
            message: string;
        };
        LotStatus: {
            gtin: string;
            lot_code?: string;
            /** @enum {string} */
            verdict: "SAFE" | "AFFECTED" | "UNKNOWN_LOT";
            incident_id?: string;
            hazard?: string;
            confidence?: number;
            /** Format: date-time */
            checked_at?: string;
        };
        MatchEvidence: {
            signal: string;
            weight: number;
            detail: string;
        };
        Match: {
            gtin: string;
            upc?: string;
            sku?: string;
            product_title?: string;
            brand?: string;
            lot_codes?: string[];
            confidence: number;
            evidence?: components["schemas"]["MatchEvidence"][];
        };
        Resolution: {
            resolution_id: string;
            incident_id: string;
            /** Format: date-time */
            resolved_at: string;
            confidence: number;
            /** @enum {string} */
            scope: "LOT" | "SKU";
            hazard?: string;
            allergens?: string[];
            classification?: string;
            matches: components["schemas"]["Match"][];
        };
    };
    responses: {
        /** @description invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolutionHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getLotStatus: {
        parameters: {
            query: {
                gtin: string;
                /** @description omit to get the SKU-level verdict */
                lot_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description verdict */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listResolutions: {
        parameters: {
            query?: {
                incident_id?: string;
                gtin?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description resolutions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Resolution"][];
                    };
                };
            };
        };
    };
}
