/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["containmentHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review queue + history */
        get: operations["listContainmentActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment/actions/{actionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContainmentAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment/actions/{actionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Human approves a below-threshold action; triggers the commerce-platform hold and emits containment.action.taken.v1 */
        post: operations["confirmContainmentAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment/actions/{actionId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectContainmentAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current auto-hold threshold (ops console threshold-tuning UI) */
        get: operations["getContainmentConfig"];
        /** @description Takes effect immediately, without redeploy. The change is itself an audited event. */
        put: operations["updateContainmentConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            /** @enum {string} */
            bus?: "up" | "down";
        };
        Error: {
            code: string;
            message: string;
        };
        ContainmentTarget: {
            gtin: string;
            sku?: string;
            product_title?: string;
            /** @enum {string} */
            scope: "LOT" | "SKU";
            lot_codes?: string[];
            confidence?: number;
        };
        ContainmentResult: {
            gtin: string;
            /** @enum {string} */
            status: "HELD" | "SKIPPED" | "FAILED" | "RELEASED";
            platform?: string;
            platform_ref?: string;
            units_held?: number;
            units_left_sellable?: number;
            error?: string;
        };
        ContainmentAction: {
            action_id: string;
            incident_id: string;
            /** @enum {string} */
            status: "PENDING_REVIEW" | "AUTO_HELD" | "HUMAN_CONFIRMED" | "HUMAN_REJECTED" | "FAILED";
            confidence: number;
            threshold: number;
            hazard?: string;
            reason?: string;
            actor?: string;
            note?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
            targets: components["schemas"]["ContainmentTarget"][];
            results?: components["schemas"]["ContainmentResult"][];
        };
        ContainmentConfig: {
            auto_hold_threshold: number;
            sku_scope_threshold: number;
            updated_by?: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description action is not in a state that allows this transition */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    containmentHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listContainmentActions: {
        parameters: {
            query?: {
                status?: "PENDING_REVIEW" | "AUTO_HELD" | "HUMAN_CONFIRMED" | "HUMAN_REJECTED" | "FAILED";
                incident_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description matching actions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ContainmentAction"][];
                    };
                };
            };
        };
    };
    getContainmentAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the action */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentAction"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    confirmContainmentAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description ops user id */
                    actor: string;
                    note?: string;
                    /** @description reviewer may narrow (never widen) the held lots */
                    lot_codes_override?: string[];
                };
            };
        };
        responses: {
            /** @description action after confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentAction"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectContainmentAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description action after rejection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentAction"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getContainmentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentConfig"];
                };
            };
        };
    };
    updateContainmentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    auto_hold_threshold: number;
                    /** @description higher bar to hold a whole SKU when no lot codes were recovered */
                    sku_scope_threshold?: number;
                    actor: string;
                };
            };
        };
        responses: {
            /** @description updated config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
